GroceryBag/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'), name='core'),
    path('store/', include('store.urls'), name='store'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from core.views import *


app_name = 'core'

urlpatterns = [
    path('', LoginView.as_view(), name='user-login'),
    path('login', LoginView.as_view(), name='user-login'),
    path('home', HomeView.as_view(), name='home'),
    path('user-logout/', UserLogout, name='user-logout'),
    path('user-register/', UserRegistrationView.as_view(), name='user-register'),

]

store/urls.py
from django.urls import path
from store.views import *


app_name = 'store'

urlpatterns = [
    path('add-item', AddItemView.as_view(), name='add-item'),
    path('update-item/<str:item_id>', UpdateItemView.as_view(), name='update-item'),
    path('delete-item/<str:item_id>', DeleteItemView.as_view(), name='delete-item'),
    path('today-items', TodayItemsView.as_view(), name='today-items'),

]

core/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from .managers import UserManager

# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    subscribed = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

store/models.py
from django.db import models

# Create your models here.


ITEM_STATUS = (
	("PENDING", "PENDING"),
	("BOUGHT", "BOUGHT"),
	("NOT AVAILABLE","NOT AVAILABLE"),
)

class Item(models.Model):
	user = models.ForeignKey('core.User', on_delete=models.PROTECT)
	name = models.CharField(max_length=20)
	quantity = models.CharField(max_length=10)
	status = models.CharField(max_length=25, choices=ITEM_STATUS)
	date = models.DateField()

core/forms.py
from django.forms import ModelForm
from django import forms
from .models import *


class UserRegistrationForm(ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'first_name', 'last_name']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserLogin(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput())

core/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.views.generic import CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from core.models import *
from .decorators import *
from store.models import *
from .forms import *


# Create your views here.


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'core/index.html'
    login_url = 'core:user-login'
    redirect_field_name = 'core:user-login'

    def get_context_data(self, **kwargs):
        items = Item.objects.filter(user=self.request.user).order_by('date')
        context = {'items': items}
        return context

    def post(self, request):
        date = request.POST['date']
        items = Item.objects.filter(date=date, user=request.user)
        return render(request, self.template_name, {'items': items})


class UserRegistrationView(CreateView):
    form_class = UserRegistrationForm
    initial = {'key': 'value'}
    template_name = 'core/user_register.html'
    @method_decorator(unauthenticated_user)
    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            # username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            messages.success(request, 'Account was created for ' + email)
            return redirect('core:user-login')
        return render(request, self.template_name, {'form': form})


class LoginView(TemplateView):
    form_class = UserLogin
    initial = {'key': 'value'}
    template_name = 'core/login.html'
    @method_decorator(unauthenticated_user)
    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        username = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('core:home')
        else:
            messages.info(request, 'Username OR Password is Incorrect')
        return render(request, 'core/login.html', {'form': form})


def UserLogout(request):
    logout(request)
    return redirect('core:user-login')

store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from core.models import *
from .models import *
from datetime import date, datetime


# Create your views here.


class AddItemView(LoginRequiredMixin, TemplateView):
    login_url = 'core:user-login'
    redirect_field_name = 'core:user-login'
    template_name = 'core/add.html'

    def post(self, request):
        name = request.POST['item_name']
        quantity = request.POST['quantity']
        status = request.POST['item_status']
        date = request.POST['date']

        items = Item.objects.create(user=request.user, name=name, quantity=quantity, status=status, date=date)
        items.save()
        messages.success(request, 'Item Add Successfully ')
        return redirect('store:add-item')


class TodayItemsView(LoginRequiredMixin, TemplateView):
    login_url = 'core:user-login'
    redirect_field_name = 'core:user-login'
    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        today = date.today()
        items = Item.objects.filter(date=today, user=self.request.user)
        context = {'items': items}
        return context


class UpdateItemView(LoginRequiredMixin, TemplateView):
    login_url = 'core:user-login'
    redirect_field_name = 'core:user-login'
    template_name = 'core/update.html'

    def get(self, request, item_id):
        item = get_object_or_404(Item, pk=item_id, user=request.user)
        # if item.user is request.user:
        context = {'item': item}
        return render(request, self.template_name, context)
        

    def post(self,request, item_id):
        name = request.POST['item_name']
        quantity = request.POST['quantity']
        status = request.POST.get('item_status')
        date = request.POST['date']


        item = get_object_or_404(Item, pk=item_id)
        items = Item.objects.filter(pk=item_id).update(user=request.user, name=name, quantity=quantity, status=status, date=date)
        # item.objects.update(user=request.user, name=name, quantity=quantity, status=status, date=date)
        
        return redirect('core:home')


class DeleteItemView(LoginRequiredMixin, TemplateView):
    login_url = 'core:user-login'
    redirect_field_name = 'core:user-login'
    template_name = 'core/index.html'

    def get(self, request, item_id):
        item = get_object_or_404(Item, pk=item_id)
        item.delete()
        return redirect('core:home')

templates/core/add.html
{% extends 'core/main.html' %}
{% block title %}Add{% endblock %}
{% load static%}

{% block content %}
<br><br><br>
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
        <div class="container mt-5">
            <h1>Add Grocery List</h1>
            <form action="{% url 'store:add-item' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label>Item name</label>
                    <input type="text" class="form-control" placeholder="Item name" name="item_name" required="True" />
                </div>
                <div class="form-group">
                    <label>Item quantity</label>
                    <input type="text" class="form-control" placeholder="Item quantity" name="quantity" required="True" />
                </div>
                <div class="form-group">
                    <label>Item status</label>
                    <select class="form-control" name="item_status">
                        <option value="PENDING">PENDING</option>
                        <option value="BOUGHT">BOUGHT</option>
                        <option value="NOT AVAILABLE">NOT AVAILABLE</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Date</label>
                    <input type="date" class="form-control" placeholder="Date" name="date" required="True">
                </div>
                <div class="form-group">
                    <input type="submit" value="Add" class="btn btn-danger">
                </div>
            </form>
        </div>
{% endblock %}

templates/core/index.html
{% extends 'core/main.html' %}
{% block title %}Home{% endblock %}
{% load static%}

{% block content %}
    <br><br>
        <div class="container mt-5">
            <!-- top -->
            <div class="row">

                <div class="col-lg-6">
                    </h3>
                    <h1>View Grocery List</h1>
                </div>
                <div class="col-lg-6 float-right">
                    <div class="row">
                        <div class="col-lg-8">
                            <!-- Date Filtering-->
                            <form action="{% url 'core:home' %}" method="POST">
                                {% csrf_token %}
                                <input type="date" class="form-control" name="date">
                                
                            
                        </div>
                        <div class="col-lg-4">
                                <input type="submit" class="btn btn-danger" value="Filter">
                                <a class="btn btn-danger" href="{% url 'store:today-items' %}">Today</a>


                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- // top -->
            <!-- Grocery Cards -->
            <div class="row mt-4">
                <!--- -->
                <!-- Loop This -->
                {% for item in items %}
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ item.name}}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">{{ item.quantity }}</h6>
                            {% if item.status == "BOUGHT" %}
                                <p class="text-success">{{ item.status }}</p>
                            {% elif item.status == "PENDING" %}
                                <p class="text-info">{{ item.status }}</p>
                            {% elif item.status == "NOT AVAILABLE" %}
                                <p class="text-danger">{{ item.status }}</p>
                            {% endif %}
                            <a href="{% url 'store:update-item' item.id %}" class="btn btn-outline-primary">Update</a>
                            <a href="{% url 'store:delete-item' item.id %}" class="btn btn-outline-danger">Delete</a>
                            <br>
                            <p style="text-align: right">{{ item.date }}</p>
                        </div>
                      </div>
                </div>
                {% endfor %}
                <!-- // Loop -->
                
            </div>
        </div>
{% endblock %}

templates/core/login.html
{% extends 'core/main.html' %}
{% block title %}Login{% endblock %}

{% block content %}
<br><br><br><br>
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
<div class="container">
    {{ filter.form }}
    <form action="{% url 'core:user-login' %}" method="POST">

        {% csrf_token %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}

            {% for error in field.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
            <p>
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <small style="color: tomato">{{ field.help_text }}</small>
                {% endif %}

            </p>
        {% endfor %}
        <input type="reset" class="btn btn-block btn-danger">
        <input type="submit" class="btn btn-block btn-primary">

    </form>
</div>

{% endblock %}

templates/core/main.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        {% load static %}
        <title>{% block title %}View List{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
        {% include 'core/navbar.html' %}
        
        {% block content %}

        {% endblock %}

        
    </body>
</html>

templates/core/navbar.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        {% load static %}
        <title>View List</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>

      <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark" >
        <a class="navbar-brand" href="#">Grocery Store</a>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
              
              
              {% if request.user.is_authenticated %}

              <a class="btn btn-outline-warning" href="{% url 'core:home' %}">Home</a>&nbsp;
              <a class="btn btn-outline-warning" href="{% url 'store:add-item' %}">Add Item</a>&nbsp;
              <a class="btn btn-outline-warning" href="{% url 'core:user-logout' %}">Logout</a>&nbsp;
              {% else %}
              <a class="btn btn-outline-warning" href="{% url 'core:user-login' %}">Login</a>&nbsp;&nbsp;
              <a class="btn btn-outline-primary" href="{% url 'core:user-register' %}">Register</a>&nbsp;
              {% endif %}

          </div>
        </div>
      </nav>
</body>
</html>

templates/core/update.html
{% extends 'core/main.html' %}
{% block title %}Update{% endblock %}
{% load static%}

{% block content %}
<br><br><br>
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
        <div class="container mt-5">
            <h1>Update Grocery List</h1>
            <form action="{% url 'store:update-item' item.id %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label>Item name</label>
                    <input type="text" class="form-control" placeholder="Item name" value="{{ item.name }}" name="item_name" />
                </div>
                <div class="form-group">
                    <label>Item quantity</label>
                    <input type="text" class="form-control" placeholder="Item quantity" value="{{ item.quantity }}" name="quantity" />
                </div>
                <div class="form-group">
                    <label>Item status</label>
                    <select class="form-control" name="item_status">
                        <option value="PENDING">PENDING</option>
                        <option value="BOUGHT">BOUGHT</option>
                        <option value="NOT AVAILABLE">NOT AVAILABLE</option>
                    </select>
                </div>
                <div class="form-group">
                    <label>Date</label>
                    <input type="date" class="form-control" placeholder="Date" value="{{ item.date }}" name="date" required="True">
                </div>
                <div class="form-group">
                    <input type="submit" value="Update" class="btn btn-danger">
                </div>
            </form>
        </div>
{% endblock %}

templates/core/user_register.html
{% extends 'core/main.html' %}
{% block title %}Register{% endblock %}

{% block content %}
<br><br><br>
<div class="container">
    <form action="{% url 'core:user-register' %}" method="POST">

        {% csrf_token %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}

            {% for error in field.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error }}</strong>
                </div>
            {% endfor %}
            <p>
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <small style="color: tomato">{{ field.help_text }}</small>
                {% endif %}

            </p>
        {% endfor %}
        <input type="reset" class="btn btn-block btn-danger">
        <input type="submit" class="btn btn-block btn-primary">

    </form>
</div>
{% endblock %}